version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: bets_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432