version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: bets_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  api:
    build: ./backend/.
    restart: always
    ports:
      - 3000:3000
  frontend:
    build: ./frontend/.
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:4000    